[*]

[gemma4-26B-A4B]
jinja = true
model = gemma-4-26B-A4B/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
model-draft = gemma-4-26B-A4B/mtp-gemma-4-26B-A4B-it.gguf
mmproj = gemma-4-26B-A4B/mmproj-F16.gguf
spec-type = draft-mtp
spec-draft-n-max = 2
alias = "gemma4-26B-A4B"
temp = 1.0
top-p = 0.95
top-k = 64
c = 64000

[qwen3.6-35B-A3B]
jinja = true
model = qwen3.6-35B-A3B/Qwen3.6-35B-A3B-UD-Q4_K_M.gguf
mmproj = qwen3.6-35B-A3B/mmproj-F16.gguf
spec-type = draft-mtp
spec-draft-n-max = 2
alias = "qwen3.6-35B-A3B"
temp = 0.7
top-p = 0.9
top-k = 20
presence-penalty = 1.5
min-p =  0.00

[nanbeige4.2-3B]
jinja = true
model = nanbeige4.2-3B/Nanbeige4.2-3B-Q4_K_M.gguf
alias = "nanbeige4.2-3B"

[laguna-s-2.1]
jinja = true
model = laguna-s-2.1/Laguna-S-2.1-MXFP4_MOE-00001-of-00003.gguf
alias = "laguna-s-2.1"

[glm-5.2]
jinja = true
model = glm-5.2/GLM-5.2-UD-IQ1_S-00001-of-00006.gguf
alias = "glm-5.2"
temp = 1.0
top-p = 0.95
min-p =  0.01

[deepseek-v4-flash]
jinja = true
model = deepseek-v4-flash/DeepSeek-V4-Flash-UD-Q8_K_XL-00001-of-00005.gguf
temp = 1.0
top-p = 1.0

[ornith-1.5-35B-A3B]
jinja = true
model = ornith-1.5-35B-A3B/Ornith-1.5-35B-Q4_K_M.gguf
mmproj = ornith-1.5-35B-A3B/mmproj-Ornith-1.5-35B-BF16.gguf
temp = 0.6
top-p = 0.95
gpu-layers = 0
device = none

[qwen3.8-27B]
jinja = true
model = qwen3.8-27B/Qwen3.8-27B-UD-Q4_K_M.gguf
mmproj = qwen3.8-27B/mmproj-F16.gguf
model-draft = qwen3.8-27B/mtp/mtp-Qwen3.8-27B-Q4_0.gguf
spec-type = draft-mtp
spec-draft-n-max = 2
alias = "qwen3.8-27B"
temp = 1.0
top-p = 0.95
top-k = 20
min-p =  0.00 

[incoai-qwen3.8-27B-dflash2]
jinja = true
model = qwen3.8-27B/Qwen3.8-27B-UD-Q4_K_M.gguf
mmproj = qwen3.8-27B/mmproj-F16.gguf
model-draft = incoai-qwen-3.8-27b-dflash2/Qwen3.8-27B-DFlash2-Q4_K_M.gguf
spec-type = draft-dflash
spec-draft-n-max = 7
alias = "incoai-qwen3.8-27B-dflash2"
temp = 1.0
top-p = 0.95
top-k = 20
min-p =  0.00 

[tiel-coder-35B-A3B]
jinja = true
#model = tiel-coder-35B-A3B/Tiel-Coder-35B-A3B-UD-Q4_K_XL.gguf
model = tiel-coder-35B-A3B/Tiel-Coder-35B-A3B-MTP-UD-Q4_K_XL.gguf
temp = 0.6
top-p = 0.95
top-k = 20
spec-type = draft-mtp
spec-draft-n-max = 1
spec-draft-p-min = 0.0

[nemotron-3-nano-4B]
jinja = true
model =  nvidia-nemotron-3-nano-4B/NVIDIA-Nemotron3-Nano-4B-Q4_K_M.gguf
